### ISSUE TITLE
Can't get it to work with a FileTable

### ISSUE THREAD

**Issue by dkearney1** [efcore/EFCore.SqlServer.HierarchyId#15]
I've got a SQL Server FileTable in a SQL Server 2012 database, which has a hierarchyid as the primary key. I'm trying to access the table, and get the following error.

```
info: EfCoreHierarchyIdTest.Worker[0]
      Worker running at: 06/11/2020 16:18:11 -07:00
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.5 initialized 'JupiterContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: using HierarchyId
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (76ms) [Parameters=[@__guid_0='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
      SELECT [s].[path_locator], [s].[cached_file_size], [s].[creation_time], [s].[file_stream], [s].[is_archive], [s].[is_directory], [s].[is_hidden], [s].[is_offline], [s].[is_readonly], [s].[is_system], [s].[is_temporary], [s].[last_access_time], [s].[last_write_time], [s].[name], [s].[parent_path_locator], [s].[stream_id]
      FROM [5Binaries].[StoredFileTableData] AS [s]
      WHERE [s].[stream_id] = @__guid_0
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'EfCoreHierarchyIdTest.EfContext.JupiterContext'.
      System.InvalidCastException: No pattern found for: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010100110010001001101111110000000
         at Microsoft.SqlServer.Types.SqlHierarchy.KnownPatterns.GetPatternByPrefix(BitReader bitR)
         at Microsoft.SqlServer.Types.SqlHierarchyId.Read(BinaryReader r)
         at Microsoft.EntityFrameworkCore.HierarchyId.Read(BinaryReader reader)
         at Microsoft.EntityFrameworkCore.SqlServer.Storage.SqlServerHierarchyIdValueConverter.fromProvider(SqlBytes bytes)
         at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
System.InvalidCastException: No pattern found for: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010100110010001001101111110000000
   at Microsoft.SqlServer.Types.SqlHierarchy.KnownPatterns.GetPatternByPrefix(BitReader bitR)
   at Microsoft.SqlServer.Types.SqlHierarchyId.Read(BinaryReader r)
   at Microsoft.EntityFrameworkCore.HierarchyId.Read(BinaryReader reader)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.SqlServerHierarchyIdValueConverter.fromProvider(SqlBytes bytes)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
```
I've verified that I can read other tables (not FileTables) from this database.
Does this error indicate I'm doing something wrong?
Is there some incompatiblity with the way FileTables implement HierarchyIds?
Is it something else altogether?

Here's my entity class
```
	public partial class StoredFileTableDatum
	{
		public Guid stream_id { get; set; }
		public byte[] file_stream { get; set; }
		public string name { get; set; }
		public HierarchyId path_locator { get; set; }
		public HierarchyId parent_path_locator { get; set; }
		public string file_type { get; }
		public long cached_file_size { get; }
		public DateTimeOffset creation_time { get; set; }
		public DateTimeOffset last_write_time { get; set; }
		public DateTimeOffset last_access_time { get; set; }
		public bool is_directory { get; set; }
		public bool is_offline { get; set; }
		public bool is_hidden { get; set; }
		public bool is_readonly { get; set; }
		public bool is_archive { get; set; }
		public bool is_system { get; set; }
		public bool is_temporary { get; set; }

		public static string ConvertGuidToHierarchyId(Guid primaryKey)
		{
			var oBytes = new List<byte>(primaryKey.ToByteArray());
			oBytes.InsertRange(0, new byte[] { 0, 0 });
			oBytes.InsertRange(8, new byte[] { 0, 0 });
			oBytes.InsertRange(16, new byte[] { 0, 0, 0, 0 });

			var b1 = oBytes.Take(8).Reverse().ToArray();
			var b2 = oBytes.Skip(8).Take(8).Reverse().ToArray();
			var b3 = oBytes.Skip(16).Take(8).Reverse().ToArray();

			var sub1 = BitConverter.ToInt64(b1, 0);
			var sub2 = BitConverter.ToInt64(b2, 0);
			var sub3 = BitConverter.ToInt64(b3, 0);

			return string.Format(CultureInfo.InvariantCulture, "/{0}.{1}.{2}/", sub1, sub2, sub3);
		}
	}
```
and my entity configuration class
```
	public sealed class StoredFileTableDatumConfiguration : IEntityTypeConfiguration<StoredFileTableDatum>
	{
		public void Configure(EntityTypeBuilder<StoredFileTableDatum> entity)
		{
			entity.ToTable("StoredFileTableData", "5Binaries");

			entity.HasKey(e => e.path_locator).IsClustered(false);

			entity.Property(e => e.stream_id).IsRequired();
			entity.Property(e => e.name).HasMaxLength(255).IsRequired();
			entity.Property(e => e.path_locator).IsRequired();
			entity.Property(e => e.parent_path_locator).ValueGeneratedOnAddOrUpdate();
			entity.Property(e => e.cached_file_size).ValueGeneratedOnAddOrUpdate();
		}
	}
```

**Comment by smitpatel** [comment]
Looking at the error message and stacktrace, it seems like something failed in `Microsoft.SqlServer.Types.SqlHierarchy` - Can you verify that it is a valid value for hierarchy id?

**Comment by dkearney1** [comment]
I can successfully retrieve the same record using SSMS, so the record is in the table. If I cast the path_locator to nvarchar(256), the value is
```
/143285890900384.246567769076225.1313277795/70366848643306.187202670003453.3813532401/265420531414585.196029540141698.1572502799/
```
That looks like a hierarchy id to me.

**Comment by smitpatel** [comment]
Can you query the data using SqlClient directly outside of EF Core?

**Comment by dkearney1** [comment]
I believe the answer is yes. This project represents an attempt to migrate existing .NET Framework C# code to EF Core. The existing code has been operational for years, working with this FileTable.

**Comment by cutig3r** [comment]
I thought I saw some similar [issues](https://github.com/dotMorten/Microsoft.SqlServer.Types/issues) in [dotMorten/Microsoft.SqlServer.Types](https://github.com/dotMorten/Microsoft.SqlServer.Types)
Particularly [#34](https://github.com/dotMorten/Microsoft.SqlServer.Types/issues/34) and [#35](https://github.com/dotMorten/Microsoft.SqlServer.Types/issues/35), so this might be covered by those.

**Comment by dkearney1** [comment]
I think you're right, @cutig3r , with #34. The underlying datatype used was a bigint/Int64.

**Comment by dkearney1** [comment]
Since @cutig3r is right that the source of the issue is that the current code assumes hierarchy ids are based on integers, I will close this issue and open one that asks when that supposition will be corrected.
