### ISSUE TITLE
HasConversion fails on DB write with DbUpdateException (InvalidCastException)

### ISSUE THREAD

**Issue by Torvin** [efcore/EFCore.SqlServer.HierarchyId#31]
Imagine I want to have `hierarchyid` as a `string` on my model. I could do this inside `OnModelCreating`:

```c#
modelBuilder
  .Entity<MyEntity>()
  .Property(x => x.HierId)
  .HasConversion(str => HierarchyId.Parse(str), id => id.ToString());
```

The reading part works fine, but writing the value back to DB throws an error:

> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
>  ---> System.InvalidCastException: Invalid cast from 'System.String' to 'Microsoft.EntityFrameworkCore.HierarchyId'.
>    at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
>    at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
>    at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
>    at System.Convert.ChangeType(Object value, Type conversionType)
>    at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
>    at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
>    at Microsoft.EntityFrameworkCore.SqlServer.Storage.SqlServerHierarchyIdTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable) in C:\Projects\EFCore.SqlServer.HierarchyId\EFCore.SqlServer.HierarchyId\Storage\SqlServerHierarchyIdTypeMapping.cs:line 100
>    at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateDbCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
>  ---> System.InvalidCastException: Invalid cast from 'System.String' to 'Microsoft.EntityFrameworkCore.HierarchyId'.
>    at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
>    at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
>    at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
>    at System.Convert.ChangeType(Object value, Type conversionType)
>    at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
>    at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
>    at Microsoft.EntityFrameworkCore.SqlServer.Storage.SqlServerHierarchyIdTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable) in C:\Projects\EFCore.SqlServer.HierarchyId\EFCore.SqlServer.HierarchyId\Storage\SqlServerHierarchyIdTypeMapping.cs:line 100
>    at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateDbCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
>    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

I've checked the base implementation of `RelationalTypeMapping.CreateParameter()` and it looks like it's supposed to call the converter before binding the parameter's value: [L495-L498](https://github.com/dotnet/efcore/blob/v5.0.0-rc.2.20475.6/src/EFCore.Relational/Storage/RelationalTypeMapping.cs#L495-L498), which the current implementation of `SqlServerHierarchyIdTypeMapping.CreateParameter()` lacks.

Here's my proposed fix:

```diff
--- a/EFCore.SqlServer.HierarchyId/Storage/SqlServerHierarchyIdTypeMapping.cs
+++ b/EFCore.SqlServer.HierarchyId/Storage/SqlServerHierarchyIdTypeMapping.cs
@@ -92,9 +92,15 @@ public override DbParameter CreateParameter(DbCommand command, string name, obje
             parameter.Direction = ParameterDirection.Input;
             parameter.ParameterName = name;

-            parameter.Value = value == null
-                ? DBNull.Value
-                : _valueConverter.ConvertToProvider(value);
+            if (value != null)
+            {
+                if (Converter != null)
+                    value = Converter.ConvertToProvider(value);
+
+                value = _valueConverter.ConvertToProvider(value);
+            }
+
+            parameter.Value = value ?? DBNull.Value;
```

**Comment by smitpatel** [comment]
EF Core does not support nested value converters. Currently https://github.com/dotnet/efcore/issues/21558 forces us to have HierarchyId with a value converter which is not known to EF Core causing issue of double value converters.
There are 2 ways to use it
- If you are writing custom value converter then write it to SqlBytes directly rather than to HierarchyId.
- EF Core combines custom value converter targeting plug in mapped type and combine both converters.

In either case, we should wait for EF Core issue to be fixed. And there is nothing to be fixed here (unless option 1 above does not work)

**Comment by Torvin** [comment]
I feel like the internal value converter is just an implementation detail and since it's not known to EF Core, it shouldn't break other stuff? Either way the overriden `CreateParameter` breaks EF Core's assumption by not employing `this.Converter` - see [another implementation](https://github.com/dotnet/efcore/blob/v5.0.0-rc.2.20475.6/src/EFCore.Relational/Storage/RelationalGeometryTypeMapping.cs#L81-L88) for example - which does exactly what I'm proposing.

**Comment by smitpatel** [comment]
Internal value converter is an implementation detail because of bug in EF Core. It is not supported design of type mapping. Using it can break other stuff in EF Core.

**Comment by Torvin** [comment]
It might be true, but that's exactly what MS is doing in their `RelationalGeometryTypeMapping` that I linked above. What you're saying is their code is using a hack. That might be true, but `SqlServerHierarchyIdTypeMapping` is using the same hack and is more broken. It should be fixed.

**Comment by smitpatel** [comment]
We will revisit this issue after https://github.com/dotnet/efcore/issues/21558 fixed if we have to do any additional work.
