### ISSUE TITLE
InvalidCastException when trying to map SQL Server File Table to entity

### ISSUE THREAD

**Issue by vbelinschi** [efcore/EFCore.SqlServer.HierarchyId#78]
Hi

I have installed this package, and created a class that corresponds to the File Table
```
 public class DocumentStore
  {
    [Column("stream_id")]
    public Guid StreamId { get; set; }

    [Column("file_stream")]
    public byte[]? FileStream { get; set; }

    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("path_locator")]
    public HierarchyId PathLocator { get; set; }

    [Column("parent_path_locator")]
    public HierarchyId? ParentPathLocator { get; set; }
    ...
    ...
  }
```
But when I try to query the table I get: 
```
System.InvalidCastException: No pattern found for: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000101101010110101011000100000
   at Microsoft.SqlServer.Types.SqlHierarchy.KnownPatterns.GetPatternByPrefix(BitReader bitR)
   at Microsoft.SqlServer.Types.SqlHierarchyId.Read(BinaryReader r)
   at Microsoft.EntityFrameworkCore.HierarchyId.Read(BinaryReader reader)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.SqlServerHierarchyIdValueConverter.fromProvider(SqlBytes bytes)
   at lambda_method9(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at BrandManagement.Persistence.Repository.BrandRepository.GetDocumentStoreAsync() in C:\dev\git\product-unik_document_server\src\BrandManagement\BrandManagement.Persistence\Repository\BrandRepository.cs:line 33
   at BrandManagement.Application.Service.BrandService.GetDSAsync() in C:\dev\git\product-unik_document_server\src\BrandManagement\BrandManagement.Application\Service\BrandService.cs:line 33
   at BrandManagement.WebApi.v1.BrandController.GetDSAsync() in C:\dev\git\product-unik_document_server\src\BrandManagement\BrandManagement.WebApi\v1\BrandController.cs:line 46
   at lambda_method4(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

If I comment out `PathLocator` and `ParentPathLocator`, it works just fine. But I need to use these fields in order to save in folders.

Any suggestions?
Thank

**Comment by bricelam** [comment]
This looks like a bug in the underlying SqlHierarchyId implementation. Please use file on [dotMorten/Microsoft.SqlServer.Types](https://github.com/dotMorten/Microsoft.SqlServer.Types) instead.

**Comment by vbelinschi** [comment]
OK, but I think the error is coming from dotMorten's package. The cast exception is being thrown from the `KnownPatterns.cs` file from that package.
And you said to use the file directly, but I get an error there as well:
```
System.InvalidOperationException: The property 'path_locator' could not be mapped because it is of type 'SqlHierarchyId', which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```
so no dice there either

**Comment by bricelam** [comment]
Sorry, I mistyped. I meant you should file a new bug on that repo so they can fix it there.
